version: '3'

services:
  drupal:
    image: drupal:8.7.2
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always
    depends_on: 
      - postgres

  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
